----아래는 system 계정에서 실행한 내용
--CREATE USER C##SUL IDENTIFIED BY 1234;
--GRANT CONNECT , RESOURCE TO C##SUL;
--ALTER USER C##SUL DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
------------------------------------------------------------------------
--------------------테이블 삭제---------------------------------------
DROP TABLE ADMIN CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER_CENTER CASCADE CONSTRAINTS;
DROP TABLE DELIVERY CASCADE CONSTRAINTS;
DROP TABLE DELIVERY_STATUS CASCADE CONSTRAINTS;

DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE ORDERS_LIST CASCADE CONSTRAINTS;
DROP TABLE CART CASCADE CONSTRAINTS;
DROP TABLE TYPE CASCADE CONSTRAINTS;

DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE ADDRESS CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE COMMUNITY CASCADE CONSTRAINTS;
DROP TABLE COMMUNITY_COMMT CASCADE CONSTRAINTS;
DROP TABLE COMMUNITY_CATEGORY CASCADE CONSTRAINTS;




------------------------시퀀스 삭제----------------------------------
DROP SEQUENCE SEQ_ADMIN_NO;
DROP SEQUENCE SEQ_NOTICE_NO;
DROP SEQUENCE SEQ_Q_NO;
DROP SEQUENCE SEQ_DELIVERY_NO;
DROP SEQUENCE SEQ_DELIVERY_STATUS_NO;

DROP SEQUENCE SEQ_PRODUCT_NO;
DROP SEQUENCE SEQ_ORDER_NO;
DROP SEQUENCE SEQ_ORDER_LIST_NO;
DROP SEQUENCE SEQ_CART_NO;
DROP SEQUENCE SEQ_TYPE_NO;

DROP SEQUENCE SEQ_MEMBER_NO;
DROP SEQUENCE SEQ_ADDRESS_NO;
DROP SEQUENCE SEQ_REVIEW_NO;
DROP SEQUENCE SEQ_COMMUNITY_NO;
DROP SEQUENCE SEQ_COMMUNITY_COMMT_NO;
DROP SEQUENCE SEQ_COMMUNITY_CATEGORY_NO;




------------------------시퀀스 생성----------------------------------
--옥진
CREATE SEQUENCE SEQ_ADMIN_NO MINVALUE 1 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_NOTICE_NO MINVALUE 1 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_Q_NO MINVALUE 1 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_DELIVERY_NO MINVALUE 1 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_DELIVERY_STATUS_NO MINVALUE 1 NOCYCLE NOCACHE;

--광포
CREATE SEQUENCE SEQ_PRODUCT_NO MINVALUE 1 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_ORDER_NO MINVALUE 1 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_ORDER_LIST_NO MINVALUE 1 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_CART_NO MINVALUE 1 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_TYPE_NO MINVALUE 1 NOCYCLE NOCACHE;



--지우
CREATE SEQUENCE SEQ_MEMBER_NO MINVALUE 1 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_ADDRESS_NO MINVALUE 1 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_REVIEW_NO MINVALUE 1 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_COMMUNITY_NO MINVALUE 1 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_COMMUNITY_COMMT_NO MINVALUE 1 NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_COMMUNITY_CATEGORY_NO MINVALUE 1 NOCYCLE NOCACHE;


------------------------테이블 생성----------------------------------
--옥진
CREATE TABLE ADMIN (
    ADMIN_NO        NUMBER                           PRIMARY KEY
    , ADMIN_ID       VARCHAR2(20)                    NOT NULL
    , ADMIN_PWD      VARCHAR2(100)                    NOT NULL
    , ADMIN_NAME     VARCHAR2(20)                    NULL
    , DEL_YN         CHAR(1)       DEFAULT 'N'       NULL
    , ENROLL_DATE    TIMESTAMP     DEFAULT SYSDATE   NULL
);

CREATE TABLE NOTICE (
   NOTICE_NO        NUMBER                          NOT NULL
   , ADMIN_NO       NUMBER                          NOT NULL
   , TITLE          VARCHAR2(100)                   NULL
   , CONTENT        VARCHAR2(100)                   NULL
   , INQUIRY        NUMBER                          NULL
   , ENROLL_DATE    TIMESTAMP     DEFAULT SYSDATE   NULL
   , UPDATE_DATE    TIMESTAMP     DEFAULT SYSDATE   NULL
   , DEL_YN         CHAR(1)       DEFAULT 'N'       NULL        
);

CREATE TABLE CUSTOMER_CENTER (
   Q_NO             NUMBER                              PRIMARY KEY
    , MEMBER_NO     NUMBER                              NOT NULL
    , Q_TITLE       VARCHAR2(100)                       NOT NULL
    , Q_CONTENT     VARCHAR2(2000)                      NOT NULL
    , Q_DATE        TIMESTAMP       DEFAULT SYSDATE     NULL
    , Q_IMG         VARCHAR2(2000)                      NULL
    , ADMIN_NO      NUMBER                              NULL
    , A_CONTENT     VARCHAR2(1000)                      NULL
    , A_DATE        TIMESTAMP       DEFAULT SYSDATE     NULL
    , A_YN          CHAR(1)         DEFAULT 'N'         NULL
);

CREATE TABLE DELIVERY (
   DELIVERY_NO               NUMBER                         PRIMARY KEY
    , DELIVERY_STATUS_NO     NUMBER                         NOT NULL
    , ORDER_NO               NUMBER                         NOT NULL
    , DELIVERY_START_DATE    TIMESTAMP   DEFAULT SYSDATE    NULL
    , DELIVERY_FINISH_DATE   VARCHAR2(1000)                 NULL
    , ADDRESS_NO             NUMBER                         NOT NULL
);

CREATE TABLE DELIVERY_STATUS (
   DELIVERY_STATUS_NO   NUMBER            PRIMARY KEY
    , DELIVERY_STATUS   VARCHAR2(20)      NULL
);


--광포
CREATE TABLE PRODUCT (
    PRODUCT_NO       NUMBER              PRIMARY KEY,
    TYPE_NO          NUMBER              NOT NULL,
    NAME             VARCHAR2(100)       NOT NULL,
    PRICE            NUMBER              NOT NULL,
    DEGREE           NUMBER              NOT NULL,
    CAPACITY         NUMBER              NOT NULL,
    EXPIRY_DATE      VARCHAR2(100)       NOT NULL,
    IMAGE            VARCHAR2(1000)      NULL,
    ENROLL_DATE      TIMESTAMP           DEFAULT SYSDATE     NOT NULL,
    DEL_YN           CHAR(1)             DEFAULT 'N'         NULL,
    STORAGE          VARCHAR2(100)       NOT NULL,
    TASTE            VARCHAR2(100)       NOT NULL,
    APPETIZER        VARCHAR2(100)       NOT NULL
);

CREATE TABLE TYPE (
    TYPE_NO          NUMBER              PRIMARY KEY,
    NAME             VARCHAR2(100)       NOT NULL
);

CREATE TABLE ORDERS (
    ORDER_NO        NUMBER              PRIMARY KEY,
    MEMBER_NO       NUMBER              NOT NULL,
    PRODUCT_NO      NUMBER              NOT NULL,
    QUANTITY        NUMBER              NOT NULL,
    ORDER_DATE      TIMESTAMP           DEFAULT SYSDATE,
    DEL_YN          CHAR(1)             DEFAULT 'N'
);

CREATE TABLE ORDERS_LIST (
    ORDER_LIST_NO    NUMBER             PRIMARY KEY,
    ORDER_NO         NUMBER             NOT NULL,
    ORDER_DATE       TIMESTAMP          DEFAULT SYSDATE,
    PRICE            NUMBER             NOT NULL,
    QUANTITY         NUMBER             NOT NULL
);

CREATE TABLE CART (
    CART_NO         NUMBER              PRIMARY KEY,
    PRODUCT_NO      NUMBER              NOT NULL,
    NAME            VARCHAR2(100)       NOT NULL,
    PRICE           NUMBER              NOT NULL,
    CAPACITY        NUMBER              NOT NULL,
    CNT             NUMBER              NOT NULL
);

--지우
CREATE TABLE MEMBER (
   MEMBER_NO       NUMBER           PRIMARY KEY,
   ADDRESS_NO NUMBER        NULL,
   NAME           VARCHAR2(10)   NULL,
   ID               VARCHAR2(10)   NOT NULL,
   PWD               VARCHAR2(100)   NULL,
   EMAIL           VARCHAR2(100)   NULL,
   NICK           VARCHAR2(100)   NULL,
   TEL               CHAR(13)       NULL,
   AGE              VARCHAR2(8)     NULL,
   ENROLL_DATE       TIMESTAMP       DEFAULT SYSDATE,
   MODIFY_DATE    TIMESTAMP       DEFAULT SYSDATE,
   DEL_YN         CHAR(1)        DEFAULT 'N'       NOT NULL   
);

CREATE TABLE ADDRESS (
   ADDRESS_NO   NUMBER           PRIMARY KEY,
   ADDRESS    VARCHAR2(100)   NULL,
   DEL_YN      CHAR(1)        DEFAULT 'N'  NOT NULL,
   MEMBER_NO   NUMBER          NOT NULL
);

CREATE TABLE REVIEW (
   REVIEW_NO       NUMBER           PRIMARY KEY,
   CONTENT           VARCHAR2(100)   NULL,
   ENROLL_DATE       TIMESTAMP       DEFAULT SYSDATE,
   IMG            VARCHAR2(100)   NULL,
   MEMBER_NO       NUMBER           NOT NULL,
   RATING           NUMBER           NULL,
   ORDER_LIST_NO       NUMBER           NOT NULL,
    DEL_YN         CHAR(1)        DEFAULT 'N'    NOT NULL   
);

CREATE TABLE COMMUNITY (
   COMMUNITY_NO   NUMBER           PRIMARY KEY,
   TITLE           VARCHAR2(100)   NULL,
   CONTENT           VARCHAR2(100)   NULL,
   ENROLL_DATE    TIMESTAMP      DEFAULT SYSDATE,
   DEL_YN         CHAR(1)        DEFAULT 'N'    NOT NULL,   
   IMG               VARCHAR2(100)   NULL,
   MEMBER_NO       NUMBER           NOT NULL,
   MODIFY_DATE       TIMESTAMP       DEFAULT SYSDATE,
  COMMUNITY_CATEGORY_NO     NUMBER          NOT NULL
);

CREATE TABLE COMMUNITY_COMMT (
   COMMUNITY_COMMT_NO       NUMBER           PRIMARY KEY,
   CONTENT           VARCHAR2(100)   NULL,
   DEL_YN         CHAR(1)        DEFAULT 'N'    NOT NULL,
   ENROLL_DATE       TIMESTAMP   DEFAULT SYSDATE,
   COMMUNITY_NO   NUMBER   NOT NULL,
   MEMBER_NO        NUMBER  NOT NULL
);

CREATE TABLE COMMUNITY_CATEGORY (
   COMMUNITY_CATEGORY_NO       NUMBER           PRIMARY KEY,
   NAME           VARCHAR2(100)   NULL,
   DEL_YN         CHAR(1)        DEFAULT 'N'    NOT NULL
);




---------------------------제약조건----------------------------------
--옥진
ALTER TABLE "NOTICE" ADD CONSTRAINT "FK_ADMIN_TO_NOTICE_1" FOREIGN KEY ("ADMIN_NO")
REFERENCES "ADMIN" ("ADMIN_NO");

ALTER TABLE "CUSTOMER_CENTER" ADD CONSTRAINT "FK_MEMBER_TO_CUSTOMER_CENTER_1" FOREIGN KEY ("MEMBER_NO")
REFERENCES "MEMBER" ("MEMBER_NO");

ALTER TABLE "CUSTOMER_CENTER" ADD CONSTRAINT "FK_ADMIN_TO_CUSTOMER_CENTER_1" FOREIGN KEY ("ADMIN_NO")
REFERENCES "ADMIN" ("ADMIN_NO");

ALTER TABLE "DELIVERY" ADD CONSTRAINT "FK_DELIVERY_STATUS_TO_DELIVERY_1" FOREIGN KEY ("DELIVERY_STATUS_NO")
REFERENCES "DELIVERY_STATUS" ("DELIVERY_STATUS_NO");

ALTER TABLE "DELIVERY" ADD CONSTRAINT "FK_ORDERS_TO_DELIVERY_1" FOREIGN KEY ("ORDER_NO")
REFERENCES "ORDERS" ("ORDER_NO");

ALTER TABLE "DELIVERY" ADD CONSTRAINT "FK_ADDRESS_TO_DELIVERY_1" FOREIGN KEY ("ADDRESS_NO")
REFERENCES "ADDRESS" ("ADDRESS_NO");


--광포
ALTER TABLE "PRODUCT" ADD CONSTRAINT "FK_TYPE_TO_PRODUCT_1" FOREIGN KEY ("TYPE_NO")
REFERENCES "TYPE" ("TYPE_NO");

ALTER TABLE "ORDERS" ADD CONSTRAINT "FK_MEMBER_TO_ORDERS_1" FOREIGN KEY ("MEMBER_NO")
REFERENCES "MEMBER" ("MEMBER_NO");
ALTER TABLE "ORDERS" ADD CONSTRAINT "FK_PRODUCT_TO_ORDERS_1" FOREIGN KEY ("PRODUCT_NO")
REFERENCES "PRODUCT" ("PRODUCT_NO");

ALTER TABLE "ORDERS_LIST" ADD CONSTRAINT "FK_ORDERS_TO_ORDER_LIST_1" FOREIGN KEY ("ORDER_NO")
REFERENCES "ORDERS" ("ORDER_NO");

ALTER TABLE "CART" ADD CONSTRAINT "FK_MEMBER_TO_CART_1" FOREIGN KEY ("MEMBER_NO")
REFERENCES "MEMBER" ("MEMBER_NO");
ALTER TABLE "CART" ADD CONSTRAINT "FK_PRODUCT_TO_CART_1" FOREIGN KEY ("PRODUCT_NO")
REFERENCES "PRODUCT" ("PRODUCT_NO");


--지우
ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_ORDERS_LIST_TO_REVIEW_1" FOREIGN KEY ("ORDER_LIST_NO")
REFERENCES "ORDERS_LIST" ("ORDER_LIST_NO");

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_MEMBER_TO_REVIEW_1" FOREIGN KEY ("MEMBER_NO")
REFERENCES "MEMBER" ("MEMBER_NO");

ALTER TABLE "ADDRESS" ADD CONSTRAINT "FK_MEMBER_TO_ADDRESS_1" FOREIGN KEY ("MEMBER_NO")
REFERENCES "MEMBER" ("MEMBER_NO");

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_ADDRESS_TO_MEMBER_1" FOREIGN KEY ("ADDRESS_NO")
REFERENCES "ADDRESS" ("ADDRESS_NO");

ALTER TABLE "COMMUNITY" ADD CONSTRAINT "FK_MEMBER_TO_COMMUNITY_1" FOREIGN KEY ("MEMBER_NO")
REFERENCES "MEMBER" ("MEMBER_NO");


ALTER TABLE "COMMUNITY_COMMT" ADD CONSTRAINT "FK_COMMUNITY_TO_COMMUNITY_COMMT_1" FOREIGN KEY ("COMMUNITY_NO")
REFERENCES "COMMUNITY" ("COMMUNITY_NO");

ALTER TABLE "COMMUNITY_COMMT" ADD CONSTRAINT "FK_MEMBER_TO_COMMUNITY_COMMT_1" FOREIGN KEY ("MEMBER_NO")
REFERENCES "MEMBER" ("MEMBER_NO");


ALTER TABLE "COMMUNITY" ADD CONSTRAINT "FK_COMMUNITY_CATEGORY_TO_COMMUNITY_1" FOREIGN KEY ("COMMUNITY_CATEGORY_NO")
REFERENCES "COMMUNITY_CATEGORY" ("COMMUNITY_CATEGORY_NO");



-----------------더미데이터-----------------------------------------------------------------------------------------
--지우

INSERT INTO MEMBER (MEMBER_NO, NAME, ID, PWD, EMAIL, NICK, TEL, AGE, DEL_YN) VALUES (SEQ_MEMBER_NO.NEXTVAL, '이름1', 'user01', '1234', 'aaa1@naver.com', 'nick01', '010-1111-1111', '20000722', 'N');
INSERT INTO MEMBER (MEMBER_NO, NAME, ID, PWD, EMAIL, NICK, TEL, AGE, DEL_YN) VALUES (SEQ_MEMBER_NO.NEXTVAL, '이름2', 'user02', '1234', 'aaa2@naver.com', 'nick02', '010-1111-1112', '19990812', 'N');
INSERT INTO MEMBER (MEMBER_NO, NAME, ID, PWD, EMAIL, NICK, TEL, AGE, DEL_YN) VALUES (SEQ_MEMBER_NO.NEXTVAL, '이름3', 'user03', '1234', 'aaa3@naver.com', 'nick03', '010-1111-1113', '20020217', 'N');
INSERT INTO MEMBER (MEMBER_NO, NAME, ID, PWD, EMAIL, NICK, TEL, AGE, DEL_YN) VALUES (SEQ_MEMBER_NO.NEXTVAL, '이름4', 'user04', '1234', 'aaa4@naver.com', 'nick04', '010-1111-1114', '19850911', 'N');
INSERT INTO MEMBER (MEMBER_NO, NAME, ID, PWD, EMAIL, NICK, TEL, AGE, DEL_YN) VALUES (SEQ_MEMBER_NO.NEXTVAL, '이름5', 'user05', '1234', 'aaa5@naver.com', 'nick05', '010-1111-1115', '19980606', 'N');

INSERT INTO ADDRESS (ADDRESS_NO, ADDRESS, DEL_YN, MEMBER_NO) VALUES (SEQ_ADDRESS_NO.NEXTVAL, '강남', 'N', 1);
INSERT INTO ADDRESS (ADDRESS_NO, ADDRESS, DEL_YN, MEMBER_NO) VALUES (SEQ_ADDRESS_NO.NEXTVAL, '목동', 'N', 2);
INSERT INTO ADDRESS (ADDRESS_NO, ADDRESS, DEL_YN, MEMBER_NO) VALUES (SEQ_ADDRESS_NO.NEXTVAL, '역삼', 'N', 1);
INSERT INTO ADDRESS (ADDRESS_NO, ADDRESS, DEL_YN, MEMBER_NO) VALUES (SEQ_ADDRESS_NO.NEXTVAL, '신정', 'N', 3);
INSERT INTO ADDRESS (ADDRESS_NO, ADDRESS, DEL_YN, MEMBER_NO) VALUES (SEQ_ADDRESS_NO.NEXTVAL, '영등포', 'N', 4);

INSERT INTO COMMUNITY_CATEGORY (COMMUNITY_CATEGORY_NO, NAME, DEL_YN) VALUES (SEQ_COMMUNITY_CATEGORY_NO.NEXTVAL, '술', 'N');
INSERT INTO COMMUNITY_CATEGORY (COMMUNITY_CATEGORY_NO, NAME, DEL_YN) VALUES (SEQ_COMMUNITY_CATEGORY_NO.NEXTVAL, '안주', 'N');

INSERT INTO COMMUNITY (COMMUNITY_NO, TITLE, CONTENT, DEL_YN, IMG, MEMBER_NO, COMMUNITY_CATEGORY_NO) VALUES (SEQ_COMMUNITY_NO.NEXTVAL, '제목1', '내용1', 'N', '이미지1', 1, 1);
INSERT INTO COMMUNITY (COMMUNITY_NO, TITLE, CONTENT, DEL_YN, IMG, MEMBER_NO, COMMUNITY_CATEGORY_NO) VALUES (SEQ_COMMUNITY_NO.NEXTVAL, '제목2', '내용2', 'N', '이미지1', 2, 2);
INSERT INTO COMMUNITY (COMMUNITY_NO, TITLE, CONTENT, DEL_YN, IMG, MEMBER_NO, COMMUNITY_CATEGORY_NO) VALUES (SEQ_COMMUNITY_NO.NEXTVAL, '제목3', '내용3', 'N', '이미지1', 3, 2);
INSERT INTO COMMUNITY (COMMUNITY_NO, TITLE, CONTENT, DEL_YN, IMG, MEMBER_NO, COMMUNITY_CATEGORY_NO) VALUES (SEQ_COMMUNITY_NO.NEXTVAL, '제목4', '내용4', 'N', '이미지1', 4, 1);
INSERT INTO COMMUNITY (COMMUNITY_NO, TITLE, CONTENT, DEL_YN, IMG, MEMBER_NO, COMMUNITY_CATEGORY_NO) VALUES (SEQ_COMMUNITY_NO.NEXTVAL, '제목5', '내용5', 'N', '이미지1', 5, 1);

INSERT INTO TYPE(TYPE_NO, NAME) VALUES(SEQ_TYPE_NO.NEXTVAL, '탁주');
INSERT INTO TYPE(TYPE_NO, NAME) VALUES(SEQ_TYPE_NO.NEXTVAL, '약.청주');
INSERT INTO TYPE(TYPE_NO, NAME) VALUES(SEQ_TYPE_NO.NEXTVAL, '과실주');
INSERT INTO TYPE(TYPE_NO, NAME) VALUES(SEQ_TYPE_NO.NEXTVAL, '증류주');

--제품
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 1, '담은', 11000, 6.5, 750, '제조일로부터 3개월', 
'세워서 냉장 보관', '우유같이 부드러운 단맛', '매콤한 음식과 즐겨보세요!')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 1, '붉은 원숭이', 9000, 10.8, 375, '제조일로부터 1년', 
'세워서 냉장 보관', '카스테라 같이 부드럽고 달콤한 맛', '가벼운 안주류와 편하게 즐겨보세요!')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 1, '백련 미스티 살균 막걸리', 4500, 7.0, 375, '제조일로부터 1년', 
'상온 보관 가능', '달콤함, 산미, 고소한 맛이 은은하게 느껴져요', '대부분의 음식과 잘 어울려요')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 1, '나주 탁주', 15000, 13.0, 500, '제조일로부터 90일', 
'냉장 보관', '묵직하고 달콤한 맛', '풍미가 강한 기름진 음식과 즐겨보세요!')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 1, '마실꾸지', 15000, 7.0, 750, '제조일로부터 30일', 
'냉장 보관', '라즈베리 주스와 같은 맛!', '묵직한 풍미의 음식과 드셔보세요')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 1, '막쿠루트', 6500, 6.0, 450, '제조일로부터 40일', 
'세워서 냉장 보관', '야쿠르트와 막걸리의 절묘한 조화!', '떡볶이와 잘어울려요~')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 1, '구름을 벗삼아', 22000, 6.0, 750, '제조일로부터 45일', 
'세워서 냉장 보관', '부드럽고 시원하게 넘어가는 단맛', '매콤한 음식과 마시기 좋아요')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 1, '호호', 15000, 9.0, 375, '병입일로부터 3개월', 
'냉장 보관', '부드러운 질감과 구수함이 마치 호박죽을 떠올리게 해요', '수분감 넘치는 음식과 드셔보세요')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 1, '문희', 27000, 13.0, 500, '제조일로부터 3개월', 
'세워서 냉장 보관', '묵직한 찹쌀의 단맛과 향!', '풍미가 짙은 육류와 잘 어울려요!')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 1, '너디 펀치', 9000, 5.0, 700, '제조일로부터 30일', 
'냉장 보관', '오렌지주스처럼 가벼운 새콤달콤함', '어린 시절 우리 입맛을 사로잡았던 음식과 함께')
;

INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 2, '고흥 유자주', 13000, 8.0, 500, '제조일로부터 10개월', 
'서늘한 곳 또는 냉장 보관', '유자차처럼 달콤한 맛', '디저트 타임 때 딱!')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 2, '서설', 15000, 13.0, 375, '유통기한 없음', 
'상온 보관', '물처럼 깔끔한 목넘김', '술맛처럼 담백한 음식과 드셔보세요')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 2, '단상지교', 20000, 16.0, 750, '병입일로부터 6개월', 
'냉장 보관', '묵직한 구수함과 진득하게 달콤한 맛', '풍미가 강한 음식들과 즐겨 보세요')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 2, '매화깊은밤', 12000, 8.0, 375, '제조일로부터 2년', 
'상온 보관', '끈적임 없이 깔끔하게 넘어가는 매실의 달콤함', '진한 풍미의 음식과 잘 어울려요')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 2, '동학', 3800, 13.0, 375, '병입일로부터 2년', 
'냉장 보관', '갓 지은 밥의 구수한 풍미를 느낄 수 있어요', '집에 있는 반찬들과 반주로 즐겨보세요')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 2, '솔송주', 9000, 13.0, 375, '제조일로부터 1년', 
'직사광선을 피하고 서늘한 곳에 보관', '달지않고 시원하게 넘어가는 약주', '바다내음 가득한 해산물요리에 시원한 솔향을 곁들여봐요')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 2, '운암 1945', 33000, 12.0, 750, '병입일로부터 2년', 
'상온 보관 가능', '달콤하기보단 톡 쏘는 신맛이 혀를 자극해요', '담백한 생선회나 기름진 음식과 즐겨보세요')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 2, '니노메', 11000, 11.0, 375, '병입일로부터 2년', 
'상온 보관 가능', '곡물의 고소함과 귤피의 씁쓸함이 돋보이는 약주', '간장 양념이 들어간 음식과 달짝지근하게 즐겨보세요')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 2, '우포', 10000, 12.0, 500, '제조일로부터 2년', 
'상온 보관 가능', '달콤하면서도 누룽지같이 고소한 끝 맛', '달콤 짭짤한 양념이 배어있는 음식과 즐겨보세요')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 2, '송이주', 15000, 13.0, 750, '제조일로부터 3년', 
'상온 보관 가능', '산림욕을 하는 듯한 솔 내음을 가득 담았어요', '기름지고 풍미 짙은 요리와 즐겨보세요')
;


INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 3, '요새로제', 17900, 6.4, 750, '병입일로부터 2년 이내', 
'상온 보관', '라즈베리의 달짝지근한 향과 새콤한 맛', '담백하거나 살짝 달콤한 음식과 즐겨보세요')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 3, '허니문배', 17900, 4.9, 750, '병입일로부터 2년 이내', 
'냉장 보관', '사과?배?꿀의 복합적인 풍미', '파티 식전주로 가볍게 즐겨보세요')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 3, '감싸주는 날', 12000, 16, 375, '제조일로부터 1년 이내', 
'냉장 보관', '단맛과 옅은 산미가 진득한 질감으로 입안을 감싸주는 술', '지방에서 비롯되는 고소한 풍미와 감칠맛을 가진 음식')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 3, '매실 향기 담은 술', 25920, 14.0, 500, '제조일로부터 3개월', 
'냉장 보관', '산뜻한 매실 풍미를 청량감 넘치게 즐겨보세요', '야들 야들한 생선회 한 점에 매향주 한 잔! 얼마나 맛있게요?')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 3, '만다린 약주', 15900, 12.0, 375, '제조일로부터 6개월', 
'냉장 보관', '계피차에 귤 과즙 한 숟갈 넣은 맛', '지방에서 비롯되는 고소한 풍미와 감칠맛을 가진 음식')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 3, '신애유자', 5900, 5.0, 330, '제조일로부터 6개월', 
'상온 보관 가능', '레모네이드 같이 싱그러운 새콤함', '부담 없이 기름진 음식과 즐겨 보세요')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 3, '허니비', 29500, 8.0, 500, '유통기한 없음', 
'냉장 보관', '계피차에 귤 과즙 한 숟갈 넣은 맛', '지방에서 비롯되는 고소한 풍미와 감칠맛을 가진 음식')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 3, '스윗마마', 5500, 5.5, 330, '병입일로부터 2년', 
'상온 보관 가능', '사과의 진한 달콤함과 시원한 탄산의 환상적인 콜라보', '달콤한 디저트와 가볍게 즐겨보세요')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 3, '혼디주', 8000, 12.0, 335, '유통기한 없음', 
'직사광선을 피하고 서늘한 곳에 보관', '감귤 계열의 새콤한 향과 달콤한 맛', '재료 본연의 맛이 느껴지는 음식과 잘 어울려요')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 3, '제주, 유채', 12000, 14.0, 375, '유통기한 없음', 
'상온 보관 가능', '달콤한 화이트 와인을 연상시켜요', '감칠맛이 짙은 음식과 드셔보세요')
;


INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 4, '서울의 밤', 7900, 25.0, 375, '유통기한 없음', 
'상온 보관 가능', '깔끔하다라는 표현이 이보다 더 잘 어울리는 술이 있을까요?', '생선회와 함께하여 극강의 깔끔함을 느껴보세요')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 4, '가평 소주', 6500, 25.0, 360, '유통기한 없음', 
'상온 보관 가능', '청주를 마신 듯한 깔끔한 목 넘김', '가평 여행을 떠올리며 바비큐와 함께 즐겨보세요')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 4, '술샘', 12000, 16.0, 375, '유통기한 없음', 
'상온 보관 가능', '알코올 향 없이 편안하게 오미자의 풍미를 느껴보세요', '다채로운 맛을 내는 오미자처럼 다양하게 즐겨보세요')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 4, '안동소주 일품', 9600, 40.0, 350, '유통기한 없음', 
'상온 보관 가능', '고소한 국물 풍미가 일품!', '거절하기 힘든 맑은 국물 요리와의 조합')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 4, '진도 아리랑 홍주', 17900, 40.0, 375, '유통기한 없음', 
'상온 보관 가능', '달콤한 꽃, 과일 향과 코를 찌르는 듯한 짜릿함을 느낄 수 있어요', '기름진 음식을 깔끔하게 즐길 수 있도록 도와줘요')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 4, '추사 40%', 67000, 40.0, 500, '유통기한 없음', 
'상온 보관 가능', '스모키한 오크향과 달콤한 사과향을 천천히 음미해보세요', '풍미 짙은 음식과 심플하면서도 화려하게 즐겨보세요')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 4, '겨울소주 25%', 10000, 25.0, 360, '유통기한 없음', 
'상온 보관 가능', '역한 맛 없이, 부드럽고 깔끔한 소주!', '취향에 맞게 다양한 음식과 즐겨보세요')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 4, '문경바람 오크 40%', 30000, 40.0, 375, '유통기한 없음', 
'상온 보관 가능', '중후한 사과의 풍미를 잔잔하게 느껴보세요', '생선회 한점과 온더락 한 모금의 여유를 만끽해보세요')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 4, '모리', 9800, 19.0, 400, '유통기한 없음', 
'상온 보관 가능', '은은한 바닐라 향이 나면서 자극적이지 않은 맛이에요', '해산물 요리와 함께하기 좋아요')
;
INSERT INTO PRODUCT(PRODUCT_NO, TYPE_NO, NAME, PRICE, DEGREE, CAPACITY, 
EXPIRY_DATE, STORAGE, TASTE, APPETIZER) 
VALUES(SEQ_PRODUCT_NO.NEXTVAL, 4, '금설', 35000, 35.0, 375, '유통기한 없음', 
'상온 보관 가능', '달짝지근한 풍미에 매운맛이 추가됐어요', '구수하면서도 달짝지근한 요리와 함께 해보세요')
;

--주문
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 1, 1, 3)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 2, 2 ,1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 3, 3, 4)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 4, 4, 2)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 5, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 6, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 7, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 8, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 9, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 10, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 11, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 12, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 13, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 14, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 15, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 16, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 17, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 18, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 19, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 20, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 21, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 22, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 23, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 24, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 25, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 26, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 27, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 28, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 29, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 30, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 31, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 32, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 33, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 34, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 35, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 36, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 37, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 38, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 39, 1)
;
INSERT INTO ORDERS(ORDER_NO, MEMBER_NO, PRODUCT_NO, QUANTITY)
VALUES(SEQ_ORDER_NO.NEXTVAL, 5, 40, 1)
;


--주문내역
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 1, 11000, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 2, 9000, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 3, 4500, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 4, 15000, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 5, 15000, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 6, 6500, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 7, 22000, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 8, 15000, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 9, 27000, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 10, 9000, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 11, 13000, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 12, 15000, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 13, 20000, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 14, 12000, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 15, 3800, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 16, 9000, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 17, 33000, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 18, 11000, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 19, 10000, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 20, 15000, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 21, 17900, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 22, 17900, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 23, 12000, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 24, 25920, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 25, 15900, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 26, 5900, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 27, 29500, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 28, 5500, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 29, 8000, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 30, 12000, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 31, 7900, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 32, 6500, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 33, 12000, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 34, 9600, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 35, 17900, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 36, 67000, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 37, 10000, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 38, 30000, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 39, 9800, 1)
;
INSERT INTO ORDERS_LIST(ORDER_LIST_NO, ORDER_NO, PRICE, QUANTITY)
VALUES(SEQ_ORDER_LIST_NO.NEXTVAL, 40, 35000, 1)
;

INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 1, 5, 'N', 1);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 2, 1, 'N', 2);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 3, 5, 'N', 3);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 4, 4, 'N', 4);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 5, 5, 'N', 5);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 1, 5, 'N', 6);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 2, 1, 'N', 7);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 3, 5, 'N', 8);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 4, 4, 'N', 9);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 5, 5, 'N', 10);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 1, 5, 'N', 11);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 2, 1, 'N', 12);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 3, 5, 'N', 13);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 4, 4, 'N', 14);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 5, 5, 'N', 15);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 1, 5, 'N', 16);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 2, 1, 'N', 17);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 3, 5, 'N', 18);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 4, 4, 'N', 19);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 5, 5, 'N', 20);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 1, 5, 'N', 21);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 2, 1, 'N', 22);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 3, 5, 'N', 23);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 4, 4, 'N', 24);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 5, 5, 'N', 25);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 1, 5, 'N', 26);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 2, 1, 'N', 27);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 3, 5, 'N', 28);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 4, 4, 'N', 29);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 5, 5, 'N', 30);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 1, 5, 'N', 31);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 2, 1, 'N', 32);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 3, 5, 'N', 33);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 4, 4, 'N', 34);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 5, 5, 'N', 35);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 1, 5, 'N', 36);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 2, 1, 'N', 37);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 3, 5, 'N', 38);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 4, 4, 'N', 39);
INSERT INTO REVIEW (REVIEW_NO, CONTENT, ENROLL_DATE, IMG, MEMBER_NO, RATING, DEL_YN, ORDER_LIST_NO) VALUES (SEQ_REVIEW_NO.NEXTVAL, '내용', '2023/12/1', '이미지1', 5, 5, 'N', 40);





INSERT INTO COMMUNITY_COMMT (COMMUNITY_COMMT_NO, CONTENT, DEL_YN,COMMUNITY_NO, MEMBER_NO) VALUES (SEQ_COMMUNITY_COMMT_NO.NEXTVAL, '댓글1', 'N', 1, 2);
INSERT INTO COMMUNITY_COMMT (COMMUNITY_COMMT_NO, CONTENT, DEL_YN, COMMUNITY_NO, MEMBER_NO) VALUES (SEQ_COMMUNITY_COMMT_NO.NEXTVAL, '댓글2', 'N', 2, 5);
INSERT INTO COMMUNITY_COMMT (COMMUNITY_COMMT_NO, CONTENT, DEL_YN, COMMUNITY_NO, MEMBER_NO) VALUES (SEQ_COMMUNITY_COMMT_NO.NEXTVAL, '댓글3', 'N', 3, 4);
INSERT INTO COMMUNITY_COMMT (COMMUNITY_COMMT_NO, CONTENT, DEL_YN, COMMUNITY_NO, MEMBER_NO) VALUES (SEQ_COMMUNITY_COMMT_NO.NEXTVAL, '댓글4', 'N', 4, 1);
INSERT INTO COMMUNITY_COMMT (COMMUNITY_COMMT_NO, CONTENT, DEL_YN, COMMUNITY_NO, MEMBER_NO) VALUES (SEQ_COMMUNITY_COMMT_NO.NEXTVAL, '댓글5', 'N', 5, 1);



--옥진
INSERT INTO ADMIN (ADMIN_NO, ADMIN_ID, ADMIN_PWD, ADMIN_NAME) VALUES(SEQ_ADMIN_NO.NEXTVAL, 'ADMIN01', '1234', '관리자01');
INSERT INTO ADMIN (ADMIN_NO, ADMIN_ID, ADMIN_PWD, ADMIN_NAME) VALUES(SEQ_ADMIN_NO.NEXTVAL, 'ADMIN02', '1234', '관리자02');
INSERT INTO ADMIN (ADMIN_NO, ADMIN_ID, ADMIN_PWD, ADMIN_NAME) VALUES(SEQ_ADMIN_NO.NEXTVAL, 'ADMIN03', '1234', '관리자03');
INSERT INTO ADMIN (ADMIN_NO, ADMIN_ID, ADMIN_PWD, ADMIN_NAME) VALUES(SEQ_ADMIN_NO.NEXTVAL, 'ADMIN04', '1234', '관리자04');
INSERT INTO ADMIN (ADMIN_NO, ADMIN_ID, ADMIN_PWD, ADMIN_NAME) VALUES(SEQ_ADMIN_NO.NEXTVAL, 'ADMIN05', '1234', '관리자05');

INSERT INTO NOTICE (NOTICE_NO, ADMIN_NO, TITLE, CONTENT, INQUIRY) VALUES(SEQ_NOTICE_NO.NEXTVAL, 1, '공지제목01', '공지내용01', 1);
INSERT INTO NOTICE (NOTICE_NO, ADMIN_NO, TITLE, CONTENT, INQUIRY) VALUES(SEQ_NOTICE_NO.NEXTVAL, 2, '공지제목02', '공지내용02', 2);
INSERT INTO NOTICE (NOTICE_NO, ADMIN_NO, TITLE, CONTENT, INQUIRY) VALUES(SEQ_NOTICE_NO.NEXTVAL, 3, '공지제목03', '공지내용03', 3);
INSERT INTO NOTICE (NOTICE_NO, ADMIN_NO, TITLE, CONTENT, INQUIRY) VALUES(SEQ_NOTICE_NO.NEXTVAL, 4, '공지제목04', '공지내용04', 4);
INSERT INTO NOTICE (NOTICE_NO, ADMIN_NO, TITLE, CONTENT, INQUIRY) VALUES(SEQ_NOTICE_NO.NEXTVAL, 5, '공지제목05', '공지내용05', 5);

INSERT INTO CUSTOMER_CENTER (Q_NO, MEMBER_NO, Q_TITLE, Q_CONTENT, ADMIN_NO, A_CONTENT) VALUES(SEQ_Q_NO.NEXTVAL, 1, '질문제목01', '질문내용01', 1, '답변내용01');
INSERT INTO CUSTOMER_CENTER (Q_NO, MEMBER_NO, Q_TITLE, Q_CONTENT, ADMIN_NO, A_CONTENT) VALUES(SEQ_Q_NO.NEXTVAL, 2, '질문제목02', '질문내용02', 2, '답변내용02');
INSERT INTO CUSTOMER_CENTER (Q_NO, MEMBER_NO, Q_TITLE, Q_CONTENT, ADMIN_NO, A_CONTENT) VALUES(SEQ_Q_NO.NEXTVAL, 3, '질문제목03', '질문내용03', 3, '답변내용03');
INSERT INTO CUSTOMER_CENTER (Q_NO, MEMBER_NO, Q_TITLE, Q_CONTENT, ADMIN_NO, A_CONTENT) VALUES(SEQ_Q_NO.NEXTVAL, 4, '질문제목04', '질문내용04', 4, '답변내용04');
INSERT INTO CUSTOMER_CENTER (Q_NO, MEMBER_NO, Q_TITLE, Q_CONTENT, ADMIN_NO, A_CONTENT) VALUES(SEQ_Q_NO.NEXTVAL, 5, '질문제목05', '질문내용05', 5, '답변내용05');

INSERT INTO DELIVERY_STATUS (DELIVERY_STATUS_NO, DELIVERY_STATUS) VALUES(SEQ_DELIVERY_STATUS_NO.NEXTVAL, '배송전');
INSERT INTO DELIVERY_STATUS (DELIVERY_STATUS_NO, DELIVERY_STATUS) VALUES(SEQ_DELIVERY_STATUS_NO.NEXTVAL, '배송중');
INSERT INTO DELIVERY_STATUS (DELIVERY_STATUS_NO, DELIVERY_STATUS) VALUES(SEQ_DELIVERY_STATUS_NO.NEXTVAL, '배송완료');


INSERT INTO DELIVERY (DELIVERY_NO, DELIVERY_STATUS_NO, ORDER_NO, ADDRESS_NO) VALUES(SEQ_DELIVERY_NO.NEXTVAL, 1, 1, 1);
INSERT INTO DELIVERY (DELIVERY_NO, DELIVERY_STATUS_NO, ORDER_NO, ADDRESS_NO) VALUES(SEQ_DELIVERY_NO.NEXTVAL, 1, 2, 2);
INSERT INTO DELIVERY (DELIVERY_NO, DELIVERY_STATUS_NO, ORDER_NO, ADDRESS_NO) VALUES(SEQ_DELIVERY_NO.NEXTVAL, 2, 3, 3);
INSERT INTO DELIVERY (DELIVERY_NO, DELIVERY_STATUS_NO, ORDER_NO, ADDRESS_NO) VALUES(SEQ_DELIVERY_NO.NEXTVAL, 2, 4, 4);
INSERT INTO DELIVERY (DELIVERY_NO, DELIVERY_STATUS_NO, ORDER_NO, ADDRESS_NO) VALUES(SEQ_DELIVERY_NO.NEXTVAL, 3, 5, 5);



--장바구니
INSERT INTO CART(CART_NO, PRODUCT_NO, NAME, PRICE, CAPACITY, CNT)
VALUES(SEQ_CART_NO.NEXTVAL, 1, '서울의밤', 7900, 375, 1)
;
INSERT INTO CART(CART_NO, PRODUCT_NO, NAME, PRICE, CAPACITY, CNT)
VALUES(SEQ_CART_NO.NEXTVAL, 2, '가평소주', 6500, 360, 1)
;
INSERT INTO CART(CART_NO, PRODUCT_NO, NAME, PRICE, CAPACITY, CNT)
VALUES(SEQ_CART_NO.NEXTVAL, 3, '담은', 11000, 750, 1)
;
INSERT INTO CART(CART_NO, PRODUCT_NO, NAME, PRICE, CAPACITY, CNT)
VALUES(SEQ_CART_NO.NEXTVAL, 4, '모리', 9800, 400, 1)
;
INSERT INTO CART(CART_NO, PRODUCT_NO, NAME, PRICE, CAPACITY, CNT)
VALUES(SEQ_CART_NO.NEXTVAL, 5, '허니문배', 17900, 750, 1)
;

COMMIT;